name: mindquest
description: A new Flutter project

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  firebase_messaging: ^14.6.0
  provider: ^6.0.4
  flutter_local_notifications: ^13.0.0
  google_fonts: ^3.0.1
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

version: 1.0.0+1